remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: [Shuhao's Data Space]
description: [Intended for storing datasets and images that can be downloaded via HTTP]
